---
- name: Install EPEL Repo package from standard repo
  yum:
    name: epel-release
    state: present
- name: install second shit
  yum:
    name: nginx
    state: latest
  tags:
      nginx-package
      packeges
- name: copypast 
  copy:
    src: nginxserv.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx
  tags:
    - nginx-configuration

- name: restart nginx
  systemd:
    name: firewalld
    state: stopped
    enabled: no


